# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Auora/Desktop/audio_effects/audio_effects.cache/wt [current_project]
set_property parent.project_path C:/Users/Auora/Desktop/audio_effects/audio_effects.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut.xci
set_property is_locked true [get_files C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top sin_lut -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all sin_lut_

write_checkpoint -force -noxdef sin_lut.dcp

catch { report_utilization -file sin_lut_utilization_synth.rpt -pb sin_lut_utilization_synth.pb }

if { [catch {
  file copy -force C:/Users/Auora/Desktop/audio_effects/audio_effects.runs/sin_lut_synth_1/sin_lut.dcp C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/Users/Auora/Desktop/audio_effects/audio_effects.ip_user_files/ip/sin_lut]} {
  catch { 
    file copy -force C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut_stub.v C:/Users/Auora/Desktop/audio_effects/audio_effects.ip_user_files/ip/sin_lut
  }
}

if {[file isdir C:/Users/Auora/Desktop/audio_effects/audio_effects.ip_user_files/ip/sin_lut]} {
  catch { 
    file copy -force C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut_stub.vhdl C:/Users/Auora/Desktop/audio_effects/audio_effects.ip_user_files/ip/sin_lut
  }
}
