# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/pitch_filter/pitch_filter.xci
# IP: The module: 'pitch_filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/pitch_filter/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'pitch_filter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/pitch_filter/pitch_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pitch_filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/pitch_filter/pitch_filter.xci
# IP: The module: 'pitch_filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/pitch_filter/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'pitch_filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/pitch_filter/pitch_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pitch_filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
