# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/fir_filter/fir_filter.xci
# IP: The module: 'fir_filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/fir_filter/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/fir_filter/fir_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/fir_filter/fir_filter.xci
# IP: The module: 'fir_filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/fir_filter/fir_compiler_v7_2_6/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Auora/Desktop/audio_effects/audio_effects.srcs/sources_1/ip/fir_filter/fir_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
