# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut.xci
# IP: The module: 'sin_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_lut'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut.xci
# IP: The module: 'sin_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Auora/Documents/tonedeaf/audio_effects.srcs/sources_1/ip/sin_lut/sin_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_lut'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
